<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnVHEUp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnVHEUp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPnVHEUp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPnVHEUp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPnVHEUp\App_KernelDevDebugContainer([
    'container.build_hash' => 'PnVHEUp',
    'container.build_id' => '7065f1dd',
    'container.build_time' => 1697224307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnVHEUp');
