<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'find_card' => [['id'], ['_controller' => 'App\\Controller\\CardController::find'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/cards']], [], [], []],
    'get_random_cards' => [[], ['_controller' => 'App\\Controller\\CardController::getRandomCards'], [], [['text', '/cards/random']], [], [], []],
];
