<?php

namespace ContainerI0RNnA1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U7bD8NjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u7bD8Nj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u7bD8Nj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', '.errored.cpYWyOW', NULL, 'Cannot determine controller argument for "App\\Controller\\CardController::getRandomCards()": the $serializer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\SerializerInterface".'],
        ], [
            'entityManager' => '?',
            'serializer' => '?',
        ]);
    }
}
