<?php

namespace ContainerI0RNnA1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CpYWyOWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.cpYWyOW' shared service.
     *
     * @return \Symfony\Component\Serializer\SerializerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\CardController::getRandomCards()": the $serializer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\SerializerInterface".');
    }
}
